# Generated by Django 5.2.7 on 2025-10-21 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Berber Adı')),
                ('telefon', models.CharField(max_length=15, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('adres', models.TextField(verbose_name='Adres')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('profil_foto', models.ImageField(blank=True, upload_to='berberler/', verbose_name='Profil Fotoğrafı')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
            ],
            options={
                'verbose_name': 'Berber',
                'verbose_name_plural': 'Berberler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100, verbose_name='Başlık')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('foto', models.ImageField(upload_to='galeri/', verbose_name='Fotoğraf')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
            ],
            options={
                'verbose_name': 'Galeri',
                'verbose_name_plural': 'Galeri',
                'ordering': ['sira', '-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Hizmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Hizmet Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Fiyat')),
                ('sure_dakika', models.PositiveIntegerField(verbose_name='Süre (Dakika)')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Iletisim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('telefon', models.CharField(max_length=15, verbose_name='Telefon')),
                ('konu', models.CharField(max_length=100, verbose_name='Konu')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('okundu', models.BooleanField(default=False, verbose_name='Okundu')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SiteAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_adi', models.CharField(default='Berber Salonu', max_length=100, verbose_name='Site Adı')),
                ('telefon', models.CharField(max_length=15, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('adres', models.TextField(verbose_name='Adres')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('logo', models.ImageField(blank=True, upload_to='site/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, upload_to='site/', verbose_name='Favicon')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('calisma_saatleri', models.TextField(verbose_name='Çalışma Saatleri')),
                ('mail_host', models.CharField(max_length=100, verbose_name='Mail Host')),
                ('mail_port', models.PositiveIntegerField(default=587, verbose_name='Mail Port')),
                ('mail_username', models.CharField(max_length=100, verbose_name='Mail Kullanıcı Adı')),
                ('mail_password', models.CharField(max_length=100, verbose_name='Mail Şifresi')),
                ('mail_use_tls', models.BooleanField(default=True, verbose_name='TLS Kullan')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, verbose_name='Soyad')),
                ('telefon', models.CharField(max_length=15, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('saat', models.TimeField(verbose_name='Saat')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('iptal', 'İptal'), ('tamamlandi', 'Tamamlandı')], default='beklemede', max_length=20, verbose_name='Durum')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('berber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berber.berber', verbose_name='Berber')),
                ('hizmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berber.hizmet', verbose_name='Hizmet')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
