# Generated by Django 5.2.7 on 2025-10-21 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HizmetTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English'), ('de', 'Deutsch')], max_length=2, verbose_name='Dil')),
                ('ad', models.CharField(blank=True, max_length=150, verbose_name='Çevrilmiş Ad')),
                ('aciklama', models.TextField(blank=True, verbose_name='Çevrilmiş Açıklama')),
                ('hizmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='berber.hizmet', verbose_name='Hizmet')),
            ],
            options={
                'verbose_name': 'Hizmet Çeviri',
                'verbose_name_plural': 'Hizmet Çevirileri',
                'unique_together': {('hizmet', 'language')},
            },
        ),
    ]
