# Generated by Django 5.2.7 on 2025-10-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berber', '0002_hizmettranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iletisim',
            name='telefon',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='telefon',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
    ]
