# Generated by Django 5.2.7 on 2025-10-22 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berber', '0003_alter_iletisim_telefon_alter_randevu_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='randevu',
            name='hizmetler',
            field=models.ManyToManyField(blank=True, related_name='randevular', to='berber.hizmet', verbose_name='Hizmetler'),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='hizmet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='berber.hizmet', verbose_name='Hizmet'),
        ),
    ]
