# Generated by Django 5.2.7 on 2025-10-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berber', '0004_randevu_hizmetler_alter_randevu_hizmet'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='google_maps_url',
            field=models.TextField(blank=True, help_text="Google Maps'ten 'Paylaş' > 'Haritayı göm' seçeneğinden alınan iframe kodunu buraya yapıştırın.", verbose_name='Google Maps Embed URL'),
        ),
    ]
