# Generated by Django 5.2.7 on 2025-10-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berber', '0005_siteayarlari_google_maps_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteayarlari',
            name='google_maps_url',
        ),
    ]
