# Generated by Django 5.2.7 on 2025-10-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berber', '0006_remove_siteayarlari_google_maps_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hizmet',
            options={'ordering': ['sira', 'ad'], 'verbose_name': 'Hizmet', 'verbose_name_plural': 'Hizmetler'},
        ),
        migrations.AddField(
            model_name='hizmet',
            name='sira',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıra'),
        ),
    ]
