# Generated by Django 5.2.7 on 2025-10-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berber', '0007_alter_hizmet_options_hizmet_sira'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='dukkan_telefon',
            field=models.CharField(blank=True, max_length=20, verbose_name='Dükkan Telefonu'),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='telefon',
            field=models.CharField(max_length=20, verbose_name='Cep Telefonu'),
        ),
    ]
