# Generated by Django 5.2.7 on 2025-10-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berber', '0008_siteayarlari_dukkan_telefon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteayarlari',
            name='mail_host',
            field=models.CharField(help_text='Örn: smtp.gmail.com, smtp.web.de', max_length=100, verbose_name='SMTP Sunucu'),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='mail_password',
            field=models.CharField(help_text='Gmail için App Password, diğer sağlayıcılar için hesap şifresi', max_length=100, verbose_name='App Password / Şifre'),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='mail_port',
            field=models.PositiveIntegerField(default=587, help_text='Genellikle 587 (TLS için)', verbose_name='SMTP Port'),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='mail_use_tls',
            field=models.BooleanField(default=True, help_text='Güvenli bağlantı için önerilir (genellikle işaretli olmalı)', verbose_name='TLS Kullan'),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='mail_username',
            field=models.CharField(help_text='Mail göndermek için kullanılacak e-posta adresi', max_length=100, verbose_name='Mail Adresi'),
        ),
    ]
