# Generated by Django 5.2.7 on 2025-10-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berber', '0009_alter_siteayarlari_mail_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteayarlari',
            name='email',
            field=models.EmailField(help_text='Müşterilerin göreceği e-posta adresi', max_length=254, verbose_name='E-posta (Sitede Görünen)'),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='mail_username',
            field=models.CharField(help_text='Randevu ve iletişim bildirimlerinin gönderileceği mail adresi (SMTP kullanıcı adı)', max_length=100, verbose_name='Yönetici Mail Adresi (SMTP)'),
        ),
    ]
