# Generated by Django 5.2.7 on 2025-10-27 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berber', '0010_alter_siteayarlari_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200, verbose_name='Yorum Yapan')),
                ('author_photo', models.URLField(blank=True, verbose_name='Profil Fotoğrafı URL')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Yıldız')),
                ('text', models.TextField(blank=True, verbose_name='Yorum Metni')),
                ('time', models.DateTimeField(verbose_name='Yorum Tarihi')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='Dil')),
                ('google_review_id', models.CharField(max_length=200, unique=True, verbose_name='Google Yorum ID')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif (Göster)')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Sisteme Eklenme')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Google Yorumu',
                'verbose_name_plural': 'Google Yorumları',
                'ordering': ['-time'],
            },
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='google_api_key',
            field=models.CharField(blank=True, help_text="Google Cloud Console'dan aldığınız API anahtarı", max_length=200, verbose_name='Google API Key'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='google_place_id',
            field=models.CharField(blank=True, help_text="Google Maps'teki işletmenizin Place ID'si", max_length=200, verbose_name='Google Place ID'),
        ),
    ]
