# Generated by Django 5.2.7 on 2025-10-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berber', '0011_googlereview_siteayarlari_google_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlereview',
            name='google_review_id',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Google Yorum ID'),
        ),
    ]
