# Generated by Django 5.2.7 on 2025-10-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berber', '0012_alter_googlereview_google_review_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleReview',
        ),
        migrations.RemoveField(
            model_name='siteayarlari',
            name='google_api_key',
        ),
        migrations.RemoveField(
            model_name='siteayarlari',
            name='google_place_id',
        ),
    ]
